name: flutternew
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  velocity_x: ^4.0.0
  google_fonts: ^6.2.1  # Updated version
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Updated version

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/
